'use strict';

const { draft } = require('../sheet');

function mortar(p) {
  return draft(Object.assign({
    kind: 'bag',
    packaging: '25 kg',
    kpis: p.kpis || [
      { value: '25 kg', label: 'saco · producto seco' },
      { value: 'Solo agua', label: 'amasado en obra' },
      { value: p.kpi3v || 'Capas de trabajo', label: p.kpi3l || 'espesor según ficha impresa' },
      { value: p.kpi4v || 'Consultar', label: p.kpi4l || 'rendimiento de referencia' },
    ],
    steps: p.steps || [
      { title: '1. Preparar el sustrato.', text: 'Firme, limpio, sin polvo, grasa ni partes sueltas. Humedecer sin saturar cuando el sustrato sea absorbente.' },
      { title: '2. Amasar.', text: 'Agregar el saco sobre agua limpia, mezclar hasta consistencia de trabajo. No añadir cemento, cal, arena ni aditivos ajenos.' },
      { title: '3. Aplicar.', text: p.apply || 'Extender con la herramienta indicada para el sistema, en el espesor de trabajo del producto.' },
      { title: '4. Curar.', text: 'Proteger de sol directo, viento y lluvia las primeras 24 h. No reamasar con agua extra la mezcla que empezó a endurecer.' },
    ],
    notes: p.notes || [
      'Esta ficha es un borrador interno: confirmar dosificación, espesores y rendimientos con la ficha impresa vigente.',
      'Un paño de prueba en el sustrato real evita sorpresas de tono, agarre y consumo.',
    ],
  }, p));
}

function liquid(p) {
  return draft(Object.assign({
    kind: 'liquid',
    packaging: p.packaging || 'Cubeta',
    kpis: p.kpis || [
      { value: 'Cubeta', label: 'presentación líquida' },
      { value: 'Listo', label: 'homogeneizar antes de usar' },
      { value: p.kpi3v || 'Brocha / rodillo', label: p.kpi3l || 'herramienta de aplicación' },
      { value: p.kpi4v || 'Consultar', label: p.kpi4l || 'rendimiento de referencia' },
    ],
    steps: p.steps || [
      { title: '1. Preparar.', text: 'Superficie limpia, firme y seca, sin polvo ni desmoldantes. Homogeneizar el envase.' },
      { title: '2. Aplicar.', text: p.apply || 'Aplicar en capa uniforme con la herramienta indicada. Respetar tiempos de secado entre manos.' },
      { title: '3. No diluir de más.', text: 'No añadir agua ni solventes ajenos salvo lo que indique la ficha impresa.' },
      { title: '4. Proteger.', text: 'Cubrir de lluvia y polvo hasta que el recubrimiento haya formado película.' },
    ],
    notes: p.notes || [
      'Producto líquido: no confundir con los morteros en saco de 25 kg.',
      'Confirmar rendimiento y número de manos con la ficha impresa vigente.',
    ],
  }, p));
}

module.exports = [
  mortar({
    slug: 'basecoat-plus-blanco',
    code: 'FT-PS-001',
    family: 'panel-system',
    name: 'BASECOAT PLUS',
    variant: 'Blanco Absoluto',
    line: 'Recubrimiento de alta protección para panel',
    accent: '#1a1a1a',
    pack: '/Assets/productos_background/basecoat-blanco.png',
    description: 'Basecoat Plus Blanco Absoluto: recubrimiento de alta protección para sistemas de panel y fachada. Saco de 25 kg.',
    strip: ['Recubrimiento para sistemas de panel', 'Blanco absoluto · saco de 25 kg'],
    lead: 'Basecoat de la línea Panel System en blanco absoluto. Recubrimiento de alta protección para paneles y fachadas, listo para amasar con agua. No es un estuco Waxtard de acabado fino: es la capa de protección del sistema de panel. Borrador interno.',
    identification: [
      { label: 'Tipo de producto', value: 'Recubrimiento base para sistemas de panel' },
      { label: 'Función', value: 'Alta protección de fachada / panel · blanco' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'Capa de recubrimiento sobre el sistema de panel. Da cuerpo, protección y una base blanca para el acabado posterior.',
      'No sustituye al adhesivo de pegado del panel ni al estuco de acabado fino de la línea Waxtard.',
    ],
    uses: [
      { title: 'Sistemas de panel.', text: 'Capa de recubrimiento sobre el tablero ya colocado.' },
      { title: 'Fachadas.', text: 'Protección de la cara expuesta antes del acabado.' },
      { title: 'Base blanca.', text: 'Cuando el acabado posterior pide fondo blanco.' },
      { title: 'No aplicar como.', text: 'Estuco de acabado aparente ni como adhesivo de pieza cerámica.' },
    ],
    apply: 'Aplicar como recubrimiento del sistema de panel, embebendo la malla si el sistema lo requiere.',
  }),

  mortar({
    slug: 'basecoat-plus-gris',
    code: 'FT-PS-002',
    family: 'panel-system',
    name: 'BASECOAT PLUS',
    variant: 'Gris',
    line: 'Recubrimiento de alta protección para panel',
    accent: '#4a4a4a',
    pack: '/Assets/productos_background/basecoat.png',
    description: 'Basecoat Plus Gris: recubrimiento de alta protección para sistemas de panel y fachada. Saco de 25 kg.',
    strip: ['Recubrimiento para sistemas de panel', 'Gris · saco de 25 kg'],
    lead: 'Basecoat de la línea Panel System en gris. Misma función de recubrimiento de alta protección que el Blanco Absoluto, en tono gris. Borrador interno.',
    identification: [
      { label: 'Tipo de producto', value: 'Recubrimiento base para sistemas de panel' },
      { label: 'Función', value: 'Alta protección de fachada / panel · gris' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'Capa de recubrimiento del sistema de panel en tono gris.',
      'Elegir blanco o gris según el acabado que va encima y el criterio de color del proyecto.',
    ],
    uses: [
      { title: 'Sistemas de panel.', text: 'Capa de recubrimiento sobre el tablero ya colocado.' },
      { title: 'Fachadas.', text: 'Protección de la cara expuesta antes del acabado.' },
      { title: 'Base gris.', text: 'Cuando el sistema posterior no requiere fondo blanco.' },
      { title: 'No aplicar como.', text: 'Estuco de acabado aparente ni como adhesivo de pieza cerámica.' },
    ],
    apply: 'Aplicar como recubrimiento del sistema de panel, embebendo la malla si el sistema lo requiere.',
  }),

  mortar({
    slug: 'styrobond-pro',
    code: 'FT-PP-001',
    family: 'pro-systems',
    name: 'STYROBOND',
    variant: 'Pro+',
    line: 'Adhesivo para sistemas de poliestireno',
    accent: '#e65100',
    pack: '/Assets/productos_background/styrobond.png',
    description: 'Styrobond Pro+: adhesivo profesional para sistemas de poliestireno y aislamiento. Saco de 25 kg.',
    strip: ['Adhesivo para poliestireno', 'Línea Pro+ · saco de 25 kg'],
    lead: 'Adhesivo de la línea Pro+ para pegar placas de poliestireno y sistemas de aislamiento. Mortero seco, listo para amasar con agua. No es un estuco de acabado. Borrador interno.',
    identification: [
      { label: 'Tipo de producto', value: 'Adhesivo cementoso para poliestireno' },
      { label: 'Función', value: 'Pegado de placas EPS / sistemas de aislamiento' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'Pega el aislante al muro. El recubrimiento del sistema (Basecoat, acabado) es otro producto.',
      'No sustituye a Cellbond (block celular) ni a los adhesivos Pegaxpress de pieza cerámica.',
    ],
    uses: [
      { title: 'Placas de poliestireno.', text: 'Pegado de EPS en sistemas de fachada y aislamiento.' },
      { title: 'Sistemas EIFS / panel.', text: 'Capa de pegado del aislante al sustrato firme.' },
      { title: 'No usar como.', text: 'Estuco de acabado, nivelador de pisos ni pegazulejo de recubrimiento.' },
      { title: 'Sustrato.', text: 'Muro firme, limpio y capaz; la placa no corrige un soporte suelto.' },
    ],
    apply: 'Aplicar al dorso de la placa o al muro según el método del sistema (cordones / full coverage).',
    kpi3v: 'Placas EPS', kpi3l: 'pegado de aislante',
  }),

  mortar({
    slug: 'cellbond-pro',
    code: 'FT-PP-002',
    family: 'pro-systems',
    name: 'CELLBOND',
    variant: 'Pro+',
    line: 'Adhesivo para block celular',
    accent: '#00897b',
    pack: '/Assets/productos_background/cellbond.png',
    description: 'Cellbond Pro+: adhesivo profesional para pegado de block celular. Saco de 25 kg.',
    strip: ['Adhesivo para block celular', 'Línea Pro+ · saco de 25 kg'],
    lead: 'Adhesivo de la línea Pro+ para asentar block celular en junta delgada. Mortero seco, listo para amasar con agua. No es un estuco ni un pegazulejo de recubrimiento. Borrador interno.',
    identification: [
      { label: 'Tipo de producto', value: 'Adhesivo cementoso para mampostería celular' },
      { label: 'Función', value: 'Pegado de block celular en junta delgada' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'Junta delgada para block celular: el adhesivo es el mortero de asiento, no un recubrimiento de muro.',
      'Para pegar block de concreto convencional el producto de la línea es Pegaxpress Block Pro+.',
    ],
    uses: [
      { title: 'Block celular.', text: 'Asiento y junta delgada en muros de block celular.' },
      { title: 'No usar como.', text: 'Estuco de acabado, recubrimiento de fachada ni pegazulejo.' },
      { title: 'Geometría.', text: 'Piezas regulares; la junta delgada no corrige desniveles grandes.' },
      { title: 'Sustrato.', text: 'Cimentación y primera hilada según el proyecto estructural.' },
    ],
    apply: 'Aplicar en cordón o capa delgada sobre la junta, asentar el block y retirar el excedente.',
    kpi3v: 'Junta delgada', kpi3l: 'asiento de block celular',
  }),

  mortar({
    slug: 'pegaxpress-block',
    code: 'FT-PP-004',
    family: 'pro-systems',
    name: 'PEGAXPRESS BLOCK',
    variant: 'Pro+',
    line: 'Adhesivo para block de concreto',
    accent: '#2e7d32',
    pack: '/Assets/productos_background/pastablock.png',
    description: 'Pegaxpress Block Pro+: adhesivo profesional para pegado de block de concreto. Saco de 25 kg.',
    strip: ['Adhesivo para block de concreto', 'Línea Pro+ · saco de 25 kg'],
    lead: 'Adhesivo de la línea Pro+ para asentar block de concreto. Mortero seco, listo para amasar con agua. Distinto de Pegaxpress PSP (piso sobre piso) y de Cellbond (block celular). Borrador interno.',
    identification: [
      { label: 'Tipo de producto', value: 'Adhesivo cementoso para mampostería de concreto' },
      { label: 'Función', value: 'Pegado de block de concreto' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'Mortero de asiento para block de concreto. No es un estuco de acabado ni un adhesivo de recubrimiento cerámico.',
      'Para block celular usar Cellbond Pro+. Para loseta sobre loseta, Pegaxpress PSP Pro+.',
    ],
    uses: [
      { title: 'Block de concreto.', text: 'Asiento y junta en muros de block.' },
      { title: 'No usar como.', text: 'Estuco, recubrimiento de fachada ni pegazulejo de piso o muro.' },
      { title: 'Geometría.', text: 'Seguir el espesor de junta del proyecto; no es un nivelador de pisos.' },
      { title: 'Sustrato.', text: 'Cimentación y arranque según el proyecto estructural.' },
    ],
    apply: 'Aplicar en la junta, asentar el block y retirar el excedente antes de que filme.',
    kpi3v: 'Block', kpi3l: 'asiento de mampostería',
  }),

  mortar({
    slug: 'porcelanico-universal',
    code: 'FT-AD-001',
    family: 'adhesivos-pro',
    name: 'PEGAXPRESS',
    variant: 'Porcelánico Universal',
    line: 'Adhesivo para porcelánico',
    accent: '#37474f',
    pack: '/Assets/productos_background/porcelanico.png',
    description: 'Pegaxpress Porcelánico Universal: adhesivo en seco para piezas de porcelánico. Saco de 25 kg.',
    strip: ['Adhesivo para porcelánico', 'Línea Pegaxpress · saco de 25 kg'],
    lead: 'Adhesivo de la línea Pegaxpress para piezas de porcelánico de baja absorción. Mortero seco, listo para amasar con agua. No es un estuco ni un nivelador. Borrador interno.',
    identification: [
      { label: 'Tipo de producto', value: 'Adhesivo cementoso para recubrimiento' },
      { label: 'Función', value: 'Pegado de porcelánico de baja absorción' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'El porcelánico absorbe poco: el adhesivo tiene que mojar el dorso y el soporte. El método (simple o doble encolado) lo define el formato y la ficha impresa.',
      'Para cerámica de mayor absorción está Pegaxpress Cerámico. Para formato exigente, Ultraforce.',
    ],
    uses: [
      { title: 'Porcelánico.', text: 'Piso y muro según formato y ficha impresa.' },
      { title: 'Baja absorción.', text: 'Piezas densas donde un adhesivo de cerámica común se queda corto.' },
      { title: 'No usar como.', text: 'Nivelador de piso, estuco de acabado ni pegado de block.' },
      { title: 'Soporte.', text: 'Firme, limpio y capaz; el adhesivo no corrige un desnivel de Leveltec.' },
    ],
    apply: 'Llana dentada al soporte; doble encolado en formatos grandes si la ficha impresa lo pide.',
    kpi3v: 'Porcelánico', kpi3l: 'piezas de baja absorción',
  }),

  mortar({
    slug: 'ceramico',
    code: 'FT-AD-002',
    family: 'adhesivos-pro',
    name: 'PEGAXPRESS',
    variant: 'Cerámico',
    line: 'Adhesivo para cerámica',
    accent: '#0277bd',
    pack: '/Assets/productos_background/ceramico.png',
    description: 'Pegaxpress Cerámico: adhesivo en seco para piezas cerámicas. Saco de 25 kg.',
    strip: ['Adhesivo para cerámica', 'Línea Pegaxpress · saco de 25 kg'],
    lead: 'Adhesivo de la línea Pegaxpress para piezas cerámicas de absorción habitual. Mortero seco, listo para amasar con agua. Para porcelánico de baja absorción usar Porcelánico Universal. Borrador interno.',
    identification: [
      { label: 'Tipo de producto', value: 'Adhesivo cementoso para recubrimiento' },
      { label: 'Función', value: 'Pegado de cerámica de absorción habitual' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'Adhesivo de uso cerámico general. No cubrir porcelánico de baja absorción ni formatos que la ficha reserve a Ultraforce.',
      'El soporte tiene que estar a plomo y nivel: el adhesivo pega, no nivela un piso.',
    ],
    uses: [
      { title: 'Loseta cerámica.', text: 'Piso y muro de absorción habitual.' },
      { title: 'No usar en.', text: 'Porcelánico de baja absorción (usar Porcelánico Universal) ni piso sobre piso (usar PSP).' },
      { title: 'No usar como.', text: 'Nivelador, estuco ni adhesivo de block.' },
      { title: 'Soporte.', text: 'Firme, limpio y capaz, dentro de las tolerancias del recubrimiento.' },
    ],
    apply: 'Llana dentada al soporte; asentar la pieza y respetar el tiempo abierto.',
    kpi3v: 'Cerámica', kpi3l: 'absorción habitual',
  }),

  mortar({
    slug: 'ultraforce',
    code: 'FT-AD-003',
    family: 'adhesivos-pro',
    name: 'PEGAXPRESS',
    variant: 'Ultraforce',
    line: 'Adhesivo de alto desempeño',
    accent: '#1a237e',
    pack: '/Assets/productos_background/ultraforce.png',
    description: 'Pegaxpress Ultraforce: adhesivo de alto desempeño para piezas exigentes. Saco de 25 kg.',
    strip: ['Adhesivo de alto desempeño', 'Línea Pegaxpress · saco de 25 kg'],
    lead: 'Adhesivo de la línea Pegaxpress para condiciones y formatos que piden más que el cerámico o el porcelánico universal: pieza grande, soporte exigente o tránsito más severo. Borrador interno: confirmar el alcance exacto con la ficha impresa.',
    identification: [
      { label: 'Tipo de producto', value: 'Adhesivo cementoso de alto desempeño' },
      { label: 'Función', value: 'Pegado de pieza exigente · formato y soporte demandantes' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'Se reserva a los casos que el cerámico y el porcelánico universal no cubren. No es el adhesivo de uso general del almacén.',
      'Tampoco es nivelador ni estuco.',
    ],
    uses: [
      { title: 'Pieza exigente.', text: 'Formatos y soportes que la ficha impresa asigne a Ultraforce.' },
      { title: 'No sustituye a.', text: 'Leveltec (nivelar), PSP (piso sobre piso) ni Block (mampostería).' },
      { title: 'No usar como.', text: 'Estuco de acabado ni recubrimiento de panel.' },
      { title: 'Soporte.', text: 'Capaz y limpio; el alto desempeño no pega sobre polvo ni sobre un firme suelto.' },
    ],
    apply: 'Llana dentada y, en formatos grandes, doble encolado si la ficha impresa lo pide.',
    kpi3v: 'Alto desempeño', kpi3l: 'formato y soporte exigentes',
  }),

  mortar({
    slug: 'pegaxpress-psp',
    code: 'FT-AD-004',
    family: 'adhesivos-pro',
    name: 'PEGAXPRESS PSP',
    variant: 'Pro+',
    line: 'Adhesivo piso sobre piso',
    accent: '#6a1b9a',
    pack: '/Assets/productos_background/piso-sobre-piso.png',
    description: 'Pegaxpress PSP Pro+: adhesivo para colocar loseta sobre loseta existente. Saco de 25 kg.',
    strip: ['Piso sobre piso', 'Línea Pegaxpress · saco de 25 kg'],
    lead: 'Adhesivo de la línea Pegaxpress para colocar recubrimiento nuevo sobre un piso cerámico existente, firme y bien adherido. No es un nivelador y no pega sobre pieza suelta. Borrador interno.',
    identification: [
      { label: 'Tipo de producto', value: 'Adhesivo cementoso para recubrimiento sobre recubrimiento' },
      { label: 'Función', value: 'Piso sobre piso · loseta sobre loseta firme' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'El soporte es la loseta vieja, no el firme. Tiene que estar sana, limpia y capaz. Si suena hueca, se levanta; no se tapa con adhesivo.',
      'Los desniveles se corrigen con Leveltec, no con PSP.',
    ],
    uses: [
      { title: 'Loseta sobre loseta.', text: 'Piso cerámico existente firme, limpio y bien adherido.' },
      { title: 'No aplicar sobre.', text: 'Pieza suelta, brillo graso sin preparar, madera, vinil o humedad activa.' },
      { title: 'No usar como.', text: 'Nivelador de firmes ni adhesivo de block.' },
      { title: 'Altura.', text: 'Verificar puertas, juntas y desniveles: se suma el espesor de adhesivo y pieza nueva.' },
    ],
    apply: 'Preparar la loseta existente (limpieza / perfilado según ficha). Llana dentada y asiento de la pieza nueva.',
    kpi3v: 'Piso sobre piso', kpi3l: 'loseta existente firme',
  }),

  liquid({
    slug: 'nanotech-hidrofobico',
    code: 'FT-LQ-001',
    family: 'liquidos',
    name: 'NANOTECH',
    variant: 'Sellador hidrofóbico',
    line: 'Sellador líquido hidrofóbico',
    accent: '#1565c0',
    pack: null,
    description: 'Nanotech Sellador Hidrofóbico: sellador líquido que repele el agua sobre superficies minerales. Cubeta.',
    strip: ['Sellador hidrofóbico', 'Líquido · cubeta'],
    lead: 'Sellador líquido de la línea Nanotech para reducir la absorción de agua en superficies minerales ya acabadas. No es un estuco, no tapa fisuras y no sustituye una impermeabilización de azotea. Borrador interno. Sin fotografía de cubeta en el repositorio.',
    identification: [
      { label: 'Tipo de producto', value: 'Sellador líquido hidrofóbico' },
      { label: 'Función', value: 'Repelencia al agua en superficies minerales' },
      { label: 'Presentación', value: 'Cubeta' },
    ],
    prose: [
      'Se aplica sobre el acabado ya curado. El agua escurre; el poro no se cierra del todo como un sellador filmógeno grueso.',
      'No corrige humedad activa ni sustituye a Waxtard como sistema de acabado hidrófugo.',
    ],
    uses: [
      { title: 'Acabados minerales.', text: 'Estucos, concretos aparentes y paños porosos ya curados.' },
      { title: 'No usar como.', text: 'Impermeabilizante de azotea, puente adhesivo ni estuco.' },
      { title: 'No aplicar sobre.', text: 'Superficies sucias, con humedad activa o con película que impida la penetración.' },
      { title: 'Prueba.', text: 'Un paño de prueba confirma tono y repelencia antes de atacar el paño completo.' },
    ],
    apply: 'Aplicar en capa uniforme sobre el acabado curado. No encharcar.',
  }),

  liquid({
    slug: 'sellador-premium-pintura',
    code: 'FT-LQ-002',
    family: 'liquidos',
    name: 'SELLADOR PREMIUM',
    variant: 'Para pintura',
    line: 'Sellador líquido para pintura',
    accent: '#f9a825',
    pack: null,
    description: 'Sellador Premium para pintura: sellador líquido de preparación de muros antes de pintar. Cubeta.',
    strip: ['Sellador para pintura', 'Líquido · cubeta'],
    lead: 'Sellador líquido para preparar muros antes de pintar: iguala absorción y mejora el anclaje de la pintura. No es hidrófugo de fachada ni un adhesivo de construcción. Borrador interno. Sin fotografía de cubeta en el repositorio.',
    identification: [
      { label: 'Tipo de producto', value: 'Sellador líquido de preparación' },
      { label: 'Función', value: 'Preparar el paño antes de pintura' },
      { label: 'Presentación', value: 'Cubeta' },
    ],
    prose: [
      'Se aplica sobre el acabado ya seco para que la pintura no manche por absorción desigual.',
      'Un acabado impermeable encima de un sistema transpirable (Waxtard) anula esa ventaja: elegir pintura permeable al vapor cuando el sistema lo pida.',
    ],
    uses: [
      { title: 'Antes de pintar.', text: 'Muros interiores y exteriores según ficha impresa.' },
      { title: 'No usar como.', text: 'Acabado final, impermeabilizante ni adhesivo de pieza.' },
      { title: 'No aplicar sobre.', text: 'Polvo, grasa, pintura suelta ni humedad activa.' },
      { title: 'Sistema.', text: 'Respetar el tiempo de secado antes de la pintura.' },
    ],
  }),

  liquid({
    slug: 'adhesivo-darawell',
    code: 'FT-LQ-003',
    family: 'liquidos',
    name: 'DARAWELL',
    variant: 'Adhesivo',
    line: 'Adhesivo líquido vinílico',
    accent: '#8d6e63',
    pack: null,
    description: 'Adhesivo Darawell: adhesivo líquido vinílico S-35. Cubeta.',
    strip: ['Adhesivo líquido vinílico', 'Cubeta'],
    lead: 'Adhesivo líquido vinílico de la línea S-35 (Darawell). No es un mortero Pegaxpress ni un estuco. Se usa como adhesivo / ligante líquido según la ficha impresa. Borrador interno. Sin fotografía de cubeta en el repositorio.',
    identification: [
      { label: 'Tipo de producto', value: 'Adhesivo líquido vinílico' },
      { label: 'Función', value: 'Pegado / ligante en sistemas que pidan Darawell' },
      { label: 'Presentación', value: 'Cubeta' },
    ],
    prose: [
      'Producto líquido. No sustituye a los adhesivos en seco de Pegaxpress para loseta o block.',
      'Homogeneizar el envase. No congelar.',
    ],
    uses: [
      { title: 'Según ficha impresa.', text: 'Pegado y ligante en los sistemas que especifiquen Darawell.' },
      { title: 'No usar como.', text: 'Pegazulejo cementoso, estuco ni impermeabilizante de azotea.' },
      { title: 'Soporte.', text: 'Limpio y capaz; el vinílico no pega sobre polvo ni sobre grasa.' },
      { title: 'Almacenamiento.', text: 'Proteger de heladas. Agitar antes de usar.' },
    ],
  }),

  liquid({
    slug: 'adhesivo-heavy-duty',
    code: 'FT-LQ-004',
    family: 'liquidos',
    name: 'HEAVY DUTY',
    variant: 'Adhesivo',
    line: 'Adhesivo líquido de alto desempeño',
    accent: '#4e342e',
    pack: null,
    description: 'Adhesivo Heavy Duty: adhesivo líquido de alto desempeño S-35. Cubeta.',
    strip: ['Adhesivo líquido de alto desempeño', 'Cubeta'],
    lead: 'Adhesivo líquido de alto desempeño. No es Pegaxpress Ultraforce (ese va en saco) ni un estuco. Borrador interno: confirmar sustratos y alcances con la ficha impresa. Sin fotografía de cubeta en el repositorio.',
    identification: [
      { label: 'Tipo de producto', value: 'Adhesivo líquido de alto desempeño' },
      { label: 'Función', value: 'Pegado exigente en sistemas que pidan Heavy Duty' },
      { label: 'Presentación', value: 'Cubeta' },
    ],
    prose: [
      'Versión líquida de alto desempeño. No confundir con Ultraforce en saco, que es adhesivo cementoso para pieza.',
      'El soporte y el tipo de pieza los define la ficha impresa, no el nombre comercial.',
    ],
    uses: [
      { title: 'Según ficha impresa.', text: 'Casos que el adhesivo vinílico estándar no cubre.' },
      { title: 'No usar como.', text: 'Estuco, nivelador de pisos ni impermeabilizante.' },
      { title: 'No sustituye a.', text: 'Pegaxpress en saco para loseta, block o piso sobre piso.' },
      { title: 'Soporte.', text: 'Limpio, firme y capaz.' },
    ],
  }),

  mortar({
    slug: 'estuco-base-pro',
    code: 'FT-LG-001',
    family: 'estucos-premium',
    legacy: true,
    name: 'ESTUCO BASE',
    variant: 'Pro+',
    line: 'Estuco base · descontinuado',
    accent: '#616161',
    pack: '/Assets/productos_background/estuco-base.png',
    description: 'Estuco Base Pro+: producto descontinuado. Fuera de catálogo.',
    strip: ['Descontinuado · fuera de catálogo', 'Saco de 25 kg'],
    lead: 'Estuco Base Pro+ está descontinuado. Esta ficha se conserva para no perder el archivo técnico. No forma parte del catálogo vigente ni del índice público. Para acabados hidrófugos de la línea actual usar Waxtard.',
    identification: [
      { label: 'Tipo de producto', value: 'Estuco base (línea anterior)' },
      { label: 'Estado', value: 'Descontinuado · fuera de catálogo' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'Producto de la línea anterior, fuera de producción comercial.',
      'No usar esta ficha para especificar obra nueva. Consultar Waxtard Blanco Perla, Blanco Absoluto, Gris o Extra Anclaje según el sustrato.',
    ],
    uses: [
      { title: 'Archivo.', text: 'Solo referencia de productos ya instalados.' },
      { title: 'Obra nueva.', text: 'Especificar la línea Waxtard vigente.' },
      { title: 'No confundir con.', text: 'Waxtard Extra Anclaje: el saco de Estuco Base no es ese producto.' },
      { title: 'Soporte.', text: 'Consultar al equipo S-35 si hay que dar mantenimiento a un paño existente.' },
    ],
    notes: [
      'Descontinuado: no aparece en el catálogo, el índice de /productos ni el sitemap.',
      'El saco de este producto se usó por error como imagen de Extra Anclaje; ya no se hace.',
    ],
  }),

  mortar({
    slug: 'mix-and-ready',
    code: 'FT-LG-002',
    family: 'pro-systems',
    legacy: true,
    name: 'MIX AND READY',
    variant: '',
    line: 'Mezcla lista · descontinuado',
    accent: '#1565c0',
    pack: '/Assets/productos_background/mixandready.png',
    description: 'Mix and Ready: producto descontinuado. Fuera de catálogo.',
    strip: ['Descontinuado · fuera de catálogo', 'Saco de 25 kg'],
    lead: 'Mix and Ready está descontinuado. Esta ficha se conserva para archivo. No forma parte del catálogo vigente ni del índice público.',
    identification: [
      { label: 'Tipo de producto', value: 'Mezcla lista (línea anterior)' },
      { label: 'Estado', value: 'Descontinuado · fuera de catálogo' },
      { label: 'Presentación', value: 'Saco de 25 kg' },
    ],
    prose: [
      'Producto de la línea anterior, fuera de producción comercial.',
      'No usar esta ficha para especificar obra nueva. Consultar la línea Pro+ y Adhesivos PRO+ vigentes.',
    ],
    uses: [
      { title: 'Archivo.', text: 'Solo referencia de productos ya instalados.' },
      { title: 'Obra nueva.', text: 'Especificar la línea vigente (Pro+ / Pegaxpress).' },
      { title: 'No confundir con.', text: 'Sellador Premium para pintura: el saco de Mix and Ready no es ese producto.' },
      { title: 'Soporte.', text: 'Consultar al equipo S-35 para mantenimiento de instalaciones existentes.' },
    ],
    notes: [
      'Descontinuado: no aparece en el catálogo, el índice de /productos ni el sitemap.',
    ],
  }),
];
