'use strict';

/**
 * Dosificaciones de planta por lote, con versiones (V1, V2…).
 * Cada versión es una receta alternativa del mismo producto (sustituciones de MP).
 * Al emitir un ticket se congela la versión usada.
 *
 * plantId → content/panel/plant-materials.js
 */
module.exports = {
  'waxtard-blanco-perla': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-waxtard',
    note: 'Lote de planta FT-PR-001. Versiones alternativas según disponibilidad de marmolina.',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Marmolina fina + gruesa',
        yieldMin: 29,
        yieldMax: 31,
        items: [
          { plantId: 'marmolina-gruesa', amount: 250, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-fina', amount: 100, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 200, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-gris', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'mortero', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 100, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 1, unit: 'Kg', role: 'Polímero' },
          { plantId: 'resina-semitski', amount: 1, unit: 'Kg', role: 'Polímero' },
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
          { plantId: 'estearato', amount: 2.5, unit: 'Kg', role: 'Aditivo' },
        ],
      },
      {
        id: 'v2',
        name: 'V2',
        label: 'Marmolina estándar (350 kg)',
        yieldMin: 29,
        yieldMax: 31,
        items: [
          { plantId: 'marmolina-estandar', amount: 350, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 200, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-gris', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'mortero', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 100, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 1, unit: 'Kg', role: 'Polímero' },
          { plantId: 'resina-semitski', amount: 1, unit: 'Kg', role: 'Polímero' },
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
          { plantId: 'estearato', amount: 2.5, unit: 'Kg', role: 'Aditivo' },
        ],
      },
    ],
  },
  'waxtard-blanco-absoluto': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-waxtard',
    note: 'Lote de planta FT-PR-002. V1 con cemento portland blanco (729 kg → ~29 sacos).',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Marmolina fina + gruesa',
        yieldMin: 28,
        yieldMax: 30,
        items: [
          { plantId: 'marmolina-gruesa', amount: 250, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-fina', amount: 100, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 200, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-blanco', amount: 75, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 100, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 1, unit: 'Kg', role: 'Polímero' },
          { plantId: 'resina-semitski', amount: 1, unit: 'Kg', role: 'Polímero' },
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
          { plantId: 'estearato', amount: 1, unit: 'Kg', role: 'Aditivo' },
        ],
      },
    ],
  },
  'waxtard-gris': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-waxtard',
    note: 'Lote de planta FT-PR-003. V1 con arena cribada fina (754 kg → ~30 sacos).',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Arena cribada fina',
        yieldMin: 29,
        yieldMax: 31,
        items: [
          { plantId: 'arena-cribada-fina', amount: 350, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 200, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-gris', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'mortero', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 100, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 1, unit: 'Kg', role: 'Polímero' },
          { plantId: 'resina-semitski', amount: 1, unit: 'Kg', role: 'Polímero' },
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
          { plantId: 'estearato', amount: 1, unit: 'Kg', role: 'Aditivo' },
        ],
      },
    ],
  },
  'waxtard-extra-anclaje': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-waxtard',
    note: 'Lote de planta FT-PR-004. V1 Estucos premium (793 kg → ~31.72 sacos).',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Marmolina fina',
        yieldMin: 31,
        yieldMax: 32,
        items: [
          { plantId: 'marmolina-fina', amount: 350, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 200, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-blanco', amount: 200, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 25, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 15, unit: 'Kg', role: 'Polímero' },
          { plantId: 'estearato', amount: 2, unit: 'Kg', role: 'Aditivo' },
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
        ],
      },
    ],
  },
  'cemento-plastico-concreto': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-MC-001. V1 Microconcreto concreto aparente (529.5 kg → ~21.18 sacos).',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Marmolina talco 200',
        yieldMin: 21,
        yieldMax: 22,
        items: [
          { plantId: 'marmolina-talco-200', amount: 300, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-gris', amount: 200, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 12.5, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 15, unit: 'Kg', role: 'Polímero' },
          { plantId: 'walocell', amount: 1.5, unit: 'Kg', role: 'Celulosa' },
          { plantId: 'estearato', amount: 0.5, unit: 'Kg', role: 'Aditivo' },
        ],
      },
    ],
  },
  'basecoat-plus-blanco': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-PS-001. V1 Panel System (842.5 kg → ~33.7 sacos). TALCO NORMAL → marmolina-talco-100 (no hay talco sin malla en catálogo).',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Marmolina fina + talco 100',
        yieldMin: 33,
        yieldMax: 34,
        items: [
          { plantId: 'marmolina-fina', amount: 400, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 200, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-blanco', amount: 200, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 25, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 15, unit: 'Kg', role: 'Polímero' },
          { plantId: 'estearato', amount: 1, unit: 'Kg', role: 'Aditivo' },
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
          { plantId: 'arbocel-celulosa', amount: 0.5, unit: 'Kg', role: 'Celulosa' },
        ],
      },
    ],
  },
  'basecoat-plus-gris': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-PS-002. V1 Panel System (841.75 kg → ~33.67 sacos). TALCO NORMAL → marmolina-talco-100 (misma regla FT-PS-001; no hay talco sin malla en catálogo).',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Marmolina fina + talco 100',
        yieldMin: 33,
        yieldMax: 34,
        items: [
          { plantId: 'marmolina-fina', amount: 400, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 200, unit: 'Kg', role: 'Carga' },
          { plantId: 'mortero', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'cemento-portland-gris', amount: 150, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 25, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 15, unit: 'Kg', role: 'Polímero' },
          { plantId: 'estearato', amount: 0.25, unit: 'Kg', role: 'Aditivo' },
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
          { plantId: 'arbocel-celulosa', amount: 0.5, unit: 'Kg', role: 'Celulosa' },
        ],
      },
    ],
  },
  ceramico: {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-AD-002. V1 Pegaxpress Cerámico (869 kg → ~34.76 sacos). ARENA DESHIDRATADA FINA → arena-deshidratada (única MP deshidratada en catálogo; no hay SKU «fina» separado).',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Arena deshidratada + talco 100',
        yieldMin: 34,
        yieldMax: 35,
        items: [
          { plantId: 'arena-deshidratada', amount: 412, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 250, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-gris', amount: 125, unit: 'Kg', role: 'Cementante' },
          { plantId: 'mortero', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 25, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 6, unit: 'Kg', role: 'Polímero' },
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
        ],
      },
    ],
  },
  'porcelanico-universal': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-AD-001. V1 Pegaxpress Porcelánico universal (748.6 kg → ~29.94 sacos). CAL → calidra. TALCO NORMAL → marmolina-talco-100 (misma regla FT-PS-001; no hay talco sin malla en catálogo).',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Marmolina gruesa + talco 100',
        yieldMin: 29,
        yieldMax: 30,
        items: [
          { plantId: 'marmolina-gruesa', amount: 412, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 100, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-gris', amount: 150, unit: 'Kg', role: 'Cementante' },
          { plantId: 'mortero', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 25, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 10, unit: 'Kg', role: 'Polímero' },
          { plantId: 'walocell', amount: 1.6, unit: 'Kg', role: 'Celulosa' },
        ],
      },
    ],
  },
  'pegaxpress-psp': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-AD-004. V1 Pegaxpress Piso sobre piso (750.6 kg → ~30.02 sacos). CAL → calidra. ARENA DESHIDRATADA → arena-deshidratada.',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Arena deshidratada + marmolina fina',
        yieldMin: 30,
        yieldMax: 30,
        items: [
          { plantId: 'arena-deshidratada', amount: 412, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-fina', amount: 100, unit: 'Kg', role: 'Agregado' },
          { plantId: 'cemento-portland-gris', amount: 150, unit: 'Kg', role: 'Cementante' },
          { plantId: 'mortero', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 25, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 12, unit: 'Kg', role: 'Polímero' },
          { plantId: 'walocell', amount: 1.6, unit: 'Kg', role: 'Celulosa' },
        ],
      },
    ],
  },
  ultraforce: {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-AD-003. V1 Pegaxpress Ultraforce (758.6 kg → ~30.34 sacos). CAL → calidra. TALCO NORMAL → marmolina-talco-100 (misma regla FT-PS-001; no hay talco sin malla en catálogo). ARENA DESHIDRATADA → arena-deshidratada.',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Arena deshidratada + talco 100',
        yieldMin: 30,
        yieldMax: 31,
        items: [
          { plantId: 'arena-deshidratada', amount: 412, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 100, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-gris', amount: 150, unit: 'Kg', role: 'Cementante' },
          { plantId: 'mortero', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 25, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 20, unit: 'Kg', role: 'Polímero' },
          { plantId: 'walocell', amount: 1.6, unit: 'Kg', role: 'Celulosa' },
        ],
      },
    ],
  },
  'pegaxpress-block': {
    mode: 'plant-lot',
    packSizeKg: 30,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-PR-006. V1 Pegaxpress Block (775 kg → ~25.83 sacos de 30 kg). ARENA → arena-cribada-fina (mejor equivalente genérico; labSlug arena-silicea-graduada). TALCO 100 → marmolina-talco-100. Saco canónico 30 kg (no 25).',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Arena cribada fina + talco 100',
        yieldMin: 25,
        yieldMax: 26,
        items: [
          { plantId: 'arena-cribada-fina', amount: 450, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 100, unit: 'Kg', role: 'Carga' },
          { plantId: 'calidra', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'cemento-portland-gris', amount: 175, unit: 'Kg', role: 'Cementante' },
        ],
      },
    ],
  },
  'leveltec-pro': {
    mode: 'plant-lot',
    packSizeKg: 35,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-PP-003. V1 Leveltec pro (518.2 kg → ~14.81 sacos de 35 kg). PELOS DE FIBRA → fibra-de-polipropileno. TALCO 100 → marmolina-talco-100. JAL CRIBADO → jal-cribado (nuevo; labSlug jal-pumita). CAL → calidra. CEMENTO → cemento-portland-gris. Saco ficha 35 kg.',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Arena fina + jal cribado + talco 100',
        yieldMin: 14,
        yieldMax: 15,
        items: [
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
          { plantId: 'resina-rdp740h', amount: 12, unit: 'Kg', role: 'Polímero' },
          { plantId: 'fibra-de-polipropileno', amount: 0.2, unit: 'Kg', role: 'Fibra' },
          { plantId: 'arena-cribada-fina', amount: 150, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 100, unit: 'Kg', role: 'Carga' },
          { plantId: 'marmolina-fina', amount: 50, unit: 'Kg', role: 'Agregado' },
          { plantId: 'jal-cribado', amount: 80, unit: 'Kg', role: 'Agregado' },
          { plantId: 'calidra', amount: 25, unit: 'Kg', role: 'Cementante' },
          { plantId: 'mortero', amount: 50, unit: 'Kg', role: 'Cementante' },
          { plantId: 'cemento-portland-gris', amount: 50, unit: 'Kg', role: 'Cementante' },
        ],
      },
    ],
  },
  'styrobond-pro': {
    mode: 'plant-lot',
    packSizeKg: 25,
    packagingPlantId: 'saco-rafia-general',
    note: 'Lote de planta FT-PP-001. V1 Styrobond pro+ (742 kg → ~29.68 sacos de 25 kg). TALCO NORMAL → marmolina-talco-100. CAL → calidra. CEMENTO BLANCO → cemento-portland-blanco.',
    defaultVersionId: 'v1',
    versions: [
      {
        id: 'v1',
        name: 'V1',
        label: 'Marmolina gruesa + fina + talco 100',
        yieldMin: 29,
        yieldMax: 30,
        items: [
          { plantId: 'marmolina-gruesa', amount: 200, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-fina', amount: 150, unit: 'Kg', role: 'Agregado' },
          { plantId: 'marmolina-talco-100', amount: 200, unit: 'Kg', role: 'Carga' },
          { plantId: 'cemento-portland-blanco', amount: 150, unit: 'Kg', role: 'Cementante' },
          { plantId: 'calidra', amount: 25, unit: 'Kg', role: 'Cementante' },
          { plantId: 'resina-rdp740h', amount: 15, unit: 'Kg', role: 'Polímero' },
          { plantId: 'estearato', amount: 1, unit: 'Kg', role: 'Aditivo' },
          { plantId: 'walocell', amount: 1, unit: 'Kg', role: 'Celulosa' },
        ],
      },
    ],
  },
};
