/**
 * Printed QR codes → material slug.
 * Keep codes short and human-typable. Unknown codes never 404.
 */
module.exports = {
  agg001: { slug: 'arena-de-rio', materialCode: 'ML-AGG-001' },
  agg002: { slug: 'perlita-expandida', materialCode: 'ML-AGG-002' },
  agg003: { slug: 'arena-silicea-graduada', materialCode: 'ML-AGG-003' },
  agg004: { slug: 'jal-pumita', materialCode: 'ML-AGG-004' },
  agg005: { slug: 'arena-de-cuarzo', materialCode: 'ML-AGG-005' },
  agg006: { slug: 'vermiculita-expandida', materialCode: 'ML-AGG-006' },
  agg007: { slug: 'vidrio-expandido', materialCode: 'ML-AGG-007' },
  agg008: { slug: 'vidrio-molido', materialCode: 'ML-AGG-008' },
  fil001: { slug: 'marmolina-fina', materialCode: 'ML-FIL-001' },
  fil002: { slug: 'carbonato-de-calcio', materialCode: 'ML-FIL-002' },
  fil003: { slug: 'dolomita', materialCode: 'ML-FIL-003' },
  fil004: { slug: 'mica', materialCode: 'ML-FIL-004' },
  fil005: { slug: 'diatomita', materialCode: 'ML-FIL-005' },
  fil006: { slug: 'barita', materialCode: 'ML-FIL-006' },
  bnd001: { slug: 'cal', materialCode: 'ML-BND-001' },
  bnd002: { slug: 'yeso', materialCode: 'ML-BND-002' },
  bnd003: { slug: 'cemento-gris', materialCode: 'ML-BND-003' },
  bnd004: { slug: 'cemento-blanco', materialCode: 'ML-BND-004' },
  bnd005: { slug: 'cemento-aluminato-de-calcio', materialCode: 'ML-BND-005' },
  bnd006: { slug: 'escoria-granulada-de-alto-horno', materialCode: 'ML-BND-006' },
  min001: { slug: 'bentonita-sodica', materialCode: 'ML-MIN-001' },
  min002: { slug: 'bentonita-granular', materialCode: 'ML-MIN-002' },
  min003: { slug: 'caolin', materialCode: 'ML-MIN-003' },
  min004: { slug: 'metacaolin', materialCode: 'ML-MIN-004' },
  min005: { slug: 'ceniza-volante', materialCode: 'ML-MIN-005' },
  min006: { slug: 'talco-silicato', materialCode: 'ML-MIN-006' },
  min007: { slug: 'puzolana-volcanica', materialCode: 'ML-MIN-007' },
  min008: { slug: 'microsilice', materialCode: 'ML-MIN-008' },
  adm001: { slug: 'celulosa-hpmc', materialCode: 'ML-ADM-001' },
  adm002: { slug: 'polimero-redispersable-vae', materialCode: 'ML-ADM-002' },
  adm003: { slug: 'eter-de-almidon', materialCode: 'ML-ADM-003' },
  pig001: { slug: 'dioxido-de-titanio', materialCode: 'ML-PIG-001' },
};
