/** Physical lots received. Exposed in UI only when characterisation exists. */
module.exports = [
  {
    id: 'ML-SMP-00001',
    materialSlug: 'arena-de-rio',
    receivedAt: '2026-08-11',
    originRegion: 'Sinaloa, MX',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00002',
    materialSlug: 'marmolina-fina',
    receivedAt: '2026-08-11',
    originRegion: 'Torreón, Coahuila, MX',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00003',
    materialSlug: 'cal',
    receivedAt: '2026-08-11',
    originRegion: 'México',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00004',
    materialSlug: 'yeso',
    receivedAt: '2026-08-11',
    originRegion: 'México',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00005',
    materialSlug: 'cemento-gris',
    receivedAt: '2026-08-11',
    originRegion: 'México',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00006',
    materialSlug: 'cemento-blanco',
    receivedAt: '2026-08-11',
    originRegion: 'México',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00007',
    materialSlug: 'perlita-expandida',
    receivedAt: '2026-08-26',
    originRegion: 'Grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00008',
    materialSlug: 'arena-silicea-graduada',
    receivedAt: '2026-08-26',
    originRegion: 'Grado comercial · clasificada por malla',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00009',
    materialSlug: 'jal-pumita',
    receivedAt: '2026-08-26',
    originRegion: 'Grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00010',
    materialSlug: 'bentonita-sodica',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00011',
    materialSlug: 'bentonita-granular',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial · gránulo compactado',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00012',
    materialSlug: 'carbonato-de-calcio',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial · caliza molida',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00013',
    materialSlug: 'arena-de-cuarzo',
    receivedAt: '2026-08-27',
    originRegion: 'Grado comercial · banco cribado, sin lavado industrial',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00014',
    materialSlug: 'dolomita',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial · carbonato doble molido',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00015',
    materialSlug: 'vermiculita-expandida',
    receivedAt: '2026-08-27',
    originRegion: 'Grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00016',
    materialSlug: 'caolin',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00017',
    materialSlug: 'metacaolin',
    receivedAt: '2026-08-27',
    originRegion: 'Grado alta reactividad',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00018',
    materialSlug: 'cemento-aluminato-de-calcio',
    receivedAt: '2026-08-27',
    originRegion: 'Grado refractario e industrial',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00019',
    materialSlug: 'celulosa-hpmc',
    receivedAt: '2026-08-27',
    originRegion: 'Aditivo funcional · grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
];
