/** Physical lots received. Exposed in UI only when characterisation exists. */
module.exports = [
  {
    id: 'ML-SMP-00001',
    materialSlug: 'arena-de-rio',
    receivedAt: '2026-08-11',
    originRegion: 'Sinaloa, MX',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00002',
    materialSlug: 'marmolina-fina',
    receivedAt: '2026-08-11',
    originRegion: 'Torreón, Coahuila, MX',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00003',
    materialSlug: 'cal',
    receivedAt: '2026-08-11',
    originRegion: 'México',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00004',
    materialSlug: 'yeso',
    receivedAt: '2026-08-11',
    originRegion: 'México',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00005',
    materialSlug: 'cemento-gris',
    receivedAt: '2026-08-11',
    originRegion: 'México',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00006',
    materialSlug: 'cemento-blanco',
    receivedAt: '2026-08-11',
    originRegion: 'México',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00007',
    materialSlug: 'perlita-expandida',
    receivedAt: '2026-08-26',
    originRegion: 'Grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00008',
    materialSlug: 'arena-silicea-graduada',
    receivedAt: '2026-08-26',
    originRegion: 'Grado comercial · clasificada por malla',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00009',
    materialSlug: 'jal-pumita',
    receivedAt: '2026-08-26',
    originRegion: 'Grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00010',
    materialSlug: 'bentonita-sodica',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00011',
    materialSlug: 'bentonita-granular',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial · gránulo compactado',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00012',
    materialSlug: 'carbonato-de-calcio',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial · caliza molida',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00013',
    materialSlug: 'arena-de-cuarzo',
    receivedAt: '2026-08-27',
    originRegion: 'Grado comercial · banco cribado, sin lavado industrial',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00014',
    materialSlug: 'dolomita',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial · carbonato doble molido',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00015',
    materialSlug: 'vermiculita-expandida',
    receivedAt: '2026-08-27',
    originRegion: 'Grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00016',
    materialSlug: 'caolin',
    receivedAt: '2026-08-27',
    originRegion: 'Grado industrial',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00017',
    materialSlug: 'metacaolin',
    receivedAt: '2026-08-27',
    originRegion: 'Grado alta reactividad',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00018',
    materialSlug: 'cemento-aluminato-de-calcio',
    receivedAt: '2026-08-27',
    originRegion: 'Grado refractario e industrial',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00019',
    materialSlug: 'celulosa-hpmc',
    receivedAt: '2026-08-27',
    originRegion: 'Aditivo funcional · grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00020',
    materialSlug: 'polimero-redispersable-vae',
    receivedAt: '2026-08-27',
    originRegion: 'Aditivo funcional · grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00021',
    materialSlug: 'eter-de-almidon',
    receivedAt: '2026-08-27',
    originRegion: 'Aditivo funcional · grado construcción',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00022',
    materialSlug: 'ceniza-volante',
    receivedAt: '2026-08-27',
    originRegion: 'Subproducto de combustión de carbón · clase F/C',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00023',
    materialSlug: 'escoria-granulada-de-alto-horno',
    receivedAt: '2026-08-27',
    originRegion: 'GGBFS · subproducto siderúrgico molido',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00024',
    materialSlug: 'diatomita',
    receivedAt: '2026-08-27',
    originRegion: 'Tierra de diatomeas, SiO₂ amorfo de origen fósil',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00025',
    materialSlug: 'barita',
    receivedAt: '2026-08-27',
    originRegion: 'Sulfato de bario, BaSO₄',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00026',
    materialSlug: 'talco-silicato',
    receivedAt: '2026-08-27',
    originRegion: 'Silicato de magnesio hidratado, Mg₃Si₄O₁₀(OH)₂',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00027',
    materialSlug: 'puzolana-volcanica',
    receivedAt: '2026-08-27',
    originRegion: 'Ceniza y roca volcánica molida, de origen natural',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00028',
    materialSlug: 'microsilice',
    receivedAt: '2026-08-27',
    originRegion: 'Silica fume · SiO₂ amorfo ultrafino',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00029',
    materialSlug: 'mica',
    receivedAt: '2026-08-27',
    originRegion: 'Filosilicato de aluminio y potasio, grupo de la moscovita',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00030',
    materialSlug: 'vidrio-expandido',
    receivedAt: '2026-08-27',
    originRegion: 'Granulado celular de vidrio reciclado, espumado térmicamente',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00031',
    materialSlug: 'vidrio-molido',
    receivedAt: '2026-08-27',
    originRegion: 'Vidrio post-consumo triturado y clasificado, GGA',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00032',
    materialSlug: 'dioxido-de-titanio',
    receivedAt: '2026-08-27',
    originRegion: 'TiO₂ rutilo/anatasa, grado recubrimientos',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00033',
    materialSlug: 'basalto',
    receivedAt: '2026-08-28',
    originRegion: 'Roca ígnea máfica, triturado de banco volcánico',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
  {
    id: 'ML-SMP-00034',
    materialSlug: 'oxido-de-hierro-rojo',
    receivedAt: '2026-08-28',
    originRegion: 'Hematita Fe₂O₃, PR101 / CI 77491',
    note: 'Referencia visual de presentación habitual. Sin ensayo instrumental de lote.',
  },
];
